=== folio-org/mod-patron/ramls/account.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Patron Account Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
      "description": "The FOLIO id of the patron"
    },
    "totalCharges": {
      "type": "object",
      "description": "A patron's total outstanding fines and charges",
      "$ref": "money.json"
    },
    "totalChargesCount": {
      "type": "integer",
      "description": "The total number of fines and charges for the patron",
      "example": "10"
    },
    "totalLoans": {
      "type": "integer",
      "description": "The total number of items loaned to the patron",
      "example": "10"
    },
    "totalHolds": {
      "type": "integer",
      "description": "The total number of requested items for the patron",
      "example": "10"
    },
    "charges": {
      "type": "array",
      "description": "A list of the patron's charges and fines",
      "items": {
        "type": "object",
        "$ref": "charge.json"
      }
    },
    "holds": {
      "type": "array",
      "description": "A list of the patron's item holds",
      "items": {
        "type": "object",
        "$ref": "hold.json"
      }
    },
    "loans": {
      "type": "array",
      "description": "A list of the patron's item checked out items",
      "items": {
        "type": "object",
        "$ref": "loan.json"
      }
    }
  },
  "required": [
    "totalCharges",
    "totalChargesCount",
    "totalLoans",
    "totalHolds",
    "charges",
    "holds",
    "loans"
  ]
}

=== folio-org/mod-patron/src/test/resources/PatronServicesResourceImpl/response_testGetPatronAccountById.json
{
    "totalCharges": {
        "amount": 155.0,
        "isoCurrencyCode": "USD"
    },
    "totalChargesCount": 4,
    "totalLoans": 3,
    "totalHolds": 3,
    "charges": [
      {
        "item" : {
          "instanceId" : "6e024cd5-c19a-4fe0-a2cd-64ce5814c694",
          "itemId" : "7d9dfe70-0158-489d-a7ed-2789eac277b3",
          "title" : "Some Book About Something",
          "author" : "Some Guy; Another Guy"
        },
        "chargeAmount" : {
          "amount" : 50.0,
          "isoCurrencyCode" : "USD"
        },
        "accrualDate" : "2018-01-31T00:00:01.000+00:00",
        "state" : "Paid Partially",
        "reason" : "damage - rebinding",
        "feeFineId" : "881c628b-e1c4-4711-b9d7-090af40f6a8f"
      }, {
        "item" : {
          "instanceId" : "75d0799a-66d8-46cf-a7e3-ed7390425112",
          "itemId" : "7d4bfd9c-dc46-46a1-89bd-160c61fe46d8",
          "title" : "This Book Is Overdue!",
          "author" : "Tempus Fugit"
        },
        "chargeAmount" : {
          "amount" : 25.0,
          "isoCurrencyCode" : "USD"
        },
        "accrualDate" : "2018-04-30T00:00:01.000+00:00",
        "state" : "Unpaid",
        "reason" : "overdue",
        "feeFineId" : "cdf3970f-7ed2-4dae-8ae3-a8250a83a9a0"
      }, {
        "item" : {
          "instanceId" : "f3482bed-a7e9-4f07-beb0-ebd693331350",
          "itemId" : "688be386-5522-4505-ad8e-60d84385d43f",
          "title" : "風の谷のナウシカ",
          "author" : "宮崎 駿"
        },
        "chargeAmount" : {
          "amount" : 5.0,
          "isoCurrencyCode" : "USD"
        },
        "accrualDate" : "2018-05-31T00:00:01.000+00:00",
        "state" : "Paid Partially",
        "reason" : "overdue",
        "feeFineId" : "cdf3970f-7ed2-4dae-8ae3-a8250a83a9a0"
      }, {
        "item" : {
          "instanceId" : "c394b514-9fd0-496d-ab9a-aec777facc1b",
          "itemId" : "240e521c-12df-4744-a5ab-313862ec1752",
          "title" : "Awesome Digital Camera",
          "author" : "Canon"
        },
        "chargeAmount" : {
          "amount" : 75.0,
          "isoCurrencyCode" : "USD"
        },
        "accrualDate" : "2018-06-01T00:00:01.000+00:00",
        "state" : "Paid Partially",
        "reason" : "damage - camera",
        "feeFineId" : "ca295e87-223f-403c-9eee-a152c47bf67f"
      }
    ],
    "holds": [
        {
            "requestId": "8bbac557-d66f-4571-bbbf-47a107cc1589",
            "item": {
                "instanceId": "255f82f3-5b1b-4239-93e4-ec6acf03ad9d",
                "itemId": "26670295-716a-4f84-8f65-2ef31707c017",
                "title": "I Want to Hold Your Hand",
                "author": "John Lennon; Paul McCartney"
            },
            "queuePosition": 1,
            "fulfillmentPreference": "Hold Shelf",
            "status": "Open - Not yet filled"
        },
        {
            "requestId": "24a5de73-859b-491f-825d-a96ea47297fb",
            "item": {
                "instanceId": "0b559683-9059-4b6d-bb6a-c55aa3518df3",
                "itemId": "dbdcb2b5-b302-4254-a55d-3c429794a4bb",
                "title": "Hold On",
                "author": "Jon Anderson; Trevor Rabin; Chris Squire"
            },
            "queuePosition": 3,
            "fulfillmentPreference": "Hold Shelf",
            "status": "Open - Awaiting pickup"
        },
        {
            "requestId": "69273dca-eacf-4225-9065-c05bbffc9d7d",
            "item": {
                "instanceId": "4bb0fffc-fe55-4445-819d-9bc5b8cd47ef",
                "itemId": "c3cfcb01-4f5d-40df-856a-c86ffe8f2d5f",
                "title": "Hold On, I'm Comin'",
                "author": "Isaac Hayes; David Porter"
            },
            "queuePosition": 5,
            "expirationDate": "2020-01-31T15:22:12Z",
            "fulfillmentPreference": "Hold Shelf",
            "status": "Open - Not yet filled"
        }
    ],
    "loans": [
        {
            "id": "9a171a89-baca-4f1a-b2c4-d7253854864e",
            "item": {
                "instanceId": "6e024cd5-c19a-4fe0-a2cd-64ce5814c694",
                "itemId": "7d9dfe70-0158-489d-a7ed-2789eac277b3",
                "title": "Some Book About Something",
                "author": "Some Guy; Another Guy"
            },
            "loanDate": "2018-06-01T11:12:00.000+00:00",
            "dueDate": "2525-01-01T11:12:00.000+00:00",
            "overdue": false
        },
        {
            "id": "76d957eb-df99-41b8-a495-d03541d079fb",
            "item": {
                "instanceId": "b3f5ef6d-2309-4935-858d-870cd7801632",
                "itemId": "7d4bfd9c-dc46-46a1-89bd-160c61fe46d8",
                "title": "This Book Is Overdue!",
                "author": "Tempus Fugit"
            },
            "loanDate": "2018-03-05T22:01:00.000+00:00",
            "dueDate": "2018-04-01T09:50:00.000+00:00",
            "overdue": true
        },
        {
            "id": "947b9387-892a-4d60-a854-a6395d0f03f0",
            "item": {
                "instanceId": "f3482bed-a7e9-4f07-beb0-ebd693331350",
                "itemId": "688be386-5522-4505-ad8e-60d84385d43f",
                "title": "風の谷のナウシカ",
                "author": "宮崎 駿"
            },
            "loanDate": "2018-06-10T16:30:00.000+00:00",
            "overdue": false
        }
    ]
}

=== folio-org/mod-patron/src/test/resources/PatronServicesResourceImpl/response_testGetPatronAccountByIdByLimitAndOffset.json
{
    "totalCharges": {
        "amount": 50.0,
        "isoCurrencyCode": "UYU"
    },
    "totalChargesCount": 1,
    "totalLoans": 1,
    "totalHolds": 1,
    "charges": [
      {
        "item" : {
          "instanceId" : "6e024cd5-c19a-4fe0-a2cd-64ce5814c694",
          "itemId" : "7d9dfe70-0158-489d-a7ed-2789eac277b3",
          "title" : "Some Book About Something",
          "author" : "Some Guy; Another Guy"
        },
        "chargeAmount" : {
          "amount" : 50.0,
          "isoCurrencyCode" : "UYU"
        },
        "accrualDate" : "2018-01-31T00:00:01.000+00:00",
        "state" : "Paid Partially",
        "reason" : "damage - rebinding"
      }
    ],
    "holds": [
        {
            "requestId": "24a5de73-859b-491f-825d-a96ea47297fb",
            "item": {
                "instanceId": "0b559683-9059-4b6d-bb6a-c55aa3518df3",
                "itemId": "dbdcb2b5-b302-4254-a55d-3c429794a4bb",
                "title": "Hold On",
                "author": "Jon Anderson; Trevor Rabin; Chris Squire"
            },
            "requestDate": "2018-05-01T05:01:15.000+00:00",
            "status": "Open - Awaiting pickup",
            "queuePosition":3
        }
    ],
    "loans": [
        {
            "id": "76d957eb-df99-41b8-a495-d03541d079fb",
            "item": {
                "instanceId": "b3f5ef6d-2309-4935-858d-870cd7801632",
                "itemId": "7d4bfd9c-dc46-46a1-89bd-160c61fe46d8",
                "title": "This Book Is Overdue!",
                "author": "Tempus Fugit"
            },
            "loanDate": "2018-03-05T22:01:00.000+00:00",
            "dueDate": "2018-04-01T09:50:00.000+00:00",
            "overdue": true
        }
    ]
}
