=== folio-org/mod-patron/ramls/batch-request-status-response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Multi-Item Request Processing Status",
  "type": "object",
  "properties": {
    "batchRequestId": {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
      "description": "The UUID id of the batch request"
    },
    "status": {
      "description": "Status of the submitted batch request",
      "type": "string",
      "enum": [
        "In progress",
        "Completed"
      ]
    },
    "submittedAt": {
      "type": "string",
      "format": "date-time",
      "description": "The date when the request was made"
    },
    "completedAt": {
      "type": "string",
      "format": "date-time",
      "description": "The date when the request was completed"
    },
    "itemsTotal": {
      "type": "integer",
      "description": "Total number of items to be requested in batch"
    },
    "itemsRequested": {
      "type": "integer",
      "description": "Number of items successfully requested"
    },
    "itemsPending": {
      "type": "integer",
      "description": "Number of items still pending to be requested"
    },
    "itemsFailed": {
      "type": "integer",
      "description": "Number of items that failed to be requested"
    },
    "itemsPendingDetails": {
      "type": "array",
      "description": "Collection of items request details that are still pending to be processed",
      "items": {
        "type": "object",
        "properties": {
          "instanceId": {
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
            "description": "The UUID id of the instance"
          },
          "itemId": {
            "description": "UUID of the item",
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
          },
          "title": {
            "description": "Title of the item",
            "type": "string"
          },
          "pickUpLocationId": {
            "description": "UUID of the pickup location",
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
          }
        }
      }
    },
    "itemsFailedDetails": {
      "type": "array",
      "description": "Collection of items request details that are failed on processing and creating requests",
      "items": {
        "type": "object",
        "properties": {
          "instanceId": {
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
            "description": "The UUID id of the instance"
          },
          "itemId": {
            "description": "UUID of the item",
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
          },
          "title": {
            "description": "Title of the item",
            "type": "string"
          },
          "pickUpLocationId": {
            "description": "UUID of the pickup location",
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
          },
          "errorCode": {
            "description": "Error code indicating the reason for failure",
            "type": "string"
          },
          "errorDetails": {
            "description": "Detailed message describing the failure",
            "type": "string"
          }
        }
      }
    },
    "itemsCompletedDetails": {
      "type": "array",
      "description": "Collection of processed and created items requests details",
      "items": {
        "type": "object",
        "properties": {
          "instanceId": {
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
            "description": "The UUID id of the instance"
          },
          "itemId": {
            "description": "UUID of the item",
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
          },
          "title": {
            "description": "Title of the item",
            "type": "string"
          },
          "pickUpLocationId": {
            "description": "UUID of the pickup location",
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
          },
          "confirmedRequestId": {
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
            "description": "The UUID id of created item request"
          }
        }
      }
    }
  },
  "required": [
    "batchRequestId",
    "status",
    "submittedAt"
  ]
}

=== folio-org/mod-patron/ramls/examples/batch-request-status-response.json
{
  "batchRequestId": "5203c035-005e-4a70-b555-ddaa3094c51c",
  "status": "Completed",
  "submittedAt": "2025-09-08T12:27:33.822+00:00",
  "completedAt": "2025-09-08T12:30:33.822+00:00",
  "itemsTotal": 3,
  "itemsRequested": 1,
  "itemsPending": 1,
  "itemsPendingDetails": [
    {
      "instanceId": "9d1b77e4-f02e-4b7f-b296-3f2042ddac54",
      "itemId": "0faa1eec-bdef-4d5e-a458-bceca8e04855",
      "title": "100 banned books: censorship histories of world literature / Nicholas J. Karolides, Margaret Bald, and Dawn B. Sova; introduction by Ken Wachsberger.",
      "pickupLocationId": "650b2d28-dc05-4177-9dc3-c45316fe5aa6"
    }
  ],
  "itemsFailed": 1,
  "itemsFailedDetails": [
    {
    "instanceId": "9d1b77e4-f02e-4b7f-b296-3f2042ddac54",
    "itemId": "0738aade-23ce-4177-8c6e-f5f13572c827",
    "title": "100 banned books: censorship histories of world literature / Nicholas J. Karolides, Margaret Bald, and Dawn B. Sova; introduction by Ken Wachsberger.",
    "pickupLocationId": "650b2d28-dc05-4177-9dc3-c45316fe5aa6",
    "errorCode": "This failed because of some internal issue",
    "errorDetails": "This failed because of some internal issue"
    },
    {
    "instanceId": "9d1b77e4-f02e-4b7f-b296-3f2042ddac54",
    "itemId": "0faa1eec-bdef-4d5e-a458-bceca8e04855",
    "title": "Something else, pt.2",
    "pickupLocationId": "650b2d28-dc05-4177-9dc3-c45316fe5aa6",
    "errorCode": "This failed because of some internal issue",
    "errorDetails": "Everything failed here, and no one knows why"
    }
  ],
  "itemsCompletedDetails": [
    {
      "instanceId": "9d1b77e4-f02e-4b7f-b296-3f2042ddac54",
      "itemId": "0faa1eec-bdef-4d5e-a458-bceca8e04855",
      "title": "100 banned books: censorship histories of world literature / Nicholas J. Karolides, Margaret Bald, and Dawn B. Sova; introduction by Ken Wachsberger.",
      "pickupLocationId": "650b2d28-dc05-4177-9dc3-c45316fe5aa6",
      "confirmedRequestId": "8d1b77e4-f02e-4b7f-b296-3f2042ddac57"
    }
  ]
}

=== folio-org/mod-patron/src/test/resources/PatronServicesResourceImpl/batch_request_status_expected_response.json
{
  "batchRequestId": "5203c035-005e-4a70-b555-ddaa3094c51c",
  "status": "In progress",
  "submittedAt": "2025-09-08T12:27:33.822+00:00",
  "itemsTotal": 2,
  "itemsRequested": 0,
  "itemsPending": 1,
  "itemsFailed": 1,
  "itemsPendingDetails": [
    {
      "instanceId": "f39fd3ca-e3fb-4cd9-8cf9-48e7e2c494e5",
      "itemId": "7e881333-3a3a-501c-a6d4-03b81e3c7e79",
      "title": "100 banned books",
      "pickUpLocationId": "ebab9ccc-4ece-4f35-bc82-01f3325abed8"
    }
  ],
  "itemsFailedDetails": [
    {
      "instanceId": "f39fd3ca-e3fb-4cd9-8cf9-48e7e2c494e5",
      "itemId": "7e881333-3a3a-501c-a6d4-03b81e3c7e79",
      "title": "100 banned books",
      "pickUpLocationId": "ebab9ccc-4ece-4f35-bc82-01f3325abed8",
      "errorDetails": "Failed due to some internal issue"
    }
  ],
  "itemsCompletedDetails": [

  ]
}
