=== folio-org/mod-patron/ramls/hold.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Patron Hold Schema",
  "type": "object",
  "description": "Hold schema for patron portal integration",
  "additionalProperties": true,
  "properties": {
    "requestId": {
      "type": "string",
      "description": "The UUID of the request"
    },
    "itemId": {
      "description": "ID of the item being requested",
      "type": "string",
      "$ref": "raml-util/schemas/uuid.schema"
    },
    "item": {
      "type": "object",
      "description": "The item  being requested",
      "$ref": "item.json"
    },
    "requestLevel": {
      "description": "Level of the request - Item or Title",
      "type": "string",
      "enum": ["Item", "Title"]
    },
    "instanceId": {
      "description": "ID of the instance being requested",
      "type": "string",
      "$ref": "raml-util/schemas/uuid.schema"
    },
    "instance": {
      "type": "object",
      "description": "The item that is checked out",
      "$ref": "instance.json"
    },
    "requester": {
      "description": "Copy of some requesting patron metadata (used for searching and sorting), will be taken from the user referred to by the requesterId",
      "type": "object",
      "properties": {
        "barcode": {
          "description": "barcode of the patron (read only, defined by the server)",
          "type": "string",
          "readonly": true
        }
      },
      "additionalProperties": false
    },
    "requestDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date when the request was made"
    },
    "expirationDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date when the request expires"
    },
    "status": {
      "type": "string",
      "description": "The status of the hold request",
      "enum": [
        "Open - Not yet filled",
        "Open - Awaiting pickup",
        "Open - In transit",
        "Closed - Filled",
        "Closed - Cancelled"
      ]
    },
    "pickupLocationId": {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
      "description": "The UUID of the pick up location"
    },
    "queuePosition": {
      "type": "integer",
      "description": "The position in the queue for this patron"
    },
    "cancellationReasonId": {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
      "description": "The id of the request reason"
    },
    "canceledByUserId": {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
      "description": "The id of the user that cancelled the request"
    },
    "cancellationAdditionalInformation": {
      "description": "Additional information about a cancellation",
      "type": "string"
    },
    "canceledDate": {
      "description": "Date the request was cancelled",
      "type": "string",
      "format": "date-time"
    },
    "patronComments": {
      "description": "Comments made by the patron",
      "type": "string"
    }
  },
  "required": [
    "requestDate",
    "pickupLocationId"
  ]
}

=== folio-org/mod-patron/src/test/resources/PatronServicesResourceImpl/response_testPostPatronAccountByIdItemByItemIdHoldCancel.json
{
    "requestId": "dd238b5b-01fc-4205-83b8-888888888888",
    "item": {
        "instanceId": "23611f0b-35cc-4f40-af09-75907d7cc421",
        "itemId": "32e5757d-6566-466e-b69d-994eb33d2b73",
        "title": "Something's Got a Hold on Me",
        "author": "Etta James; Leroy Kirkland; Pearl Woods"
    },
    "requestDate": "2018-05-30T08:01:30Z",
    "expirationDate": "3000-01-30T08:16:30Z",
    "status": "Closed - Cancelled",
    "cancellationReasonId": "b548b182-55c2-4741-b169-616d9cd995a8",
    "canceledByUserId": "ab5a5c57-491c-4b08-8f39-907810e14913",
    "cancellationAdditionalInformation": "I don't want it anymore",
    "canceledDate": "2019-11-06T16:23:30.262+0000",
    "pickupLocationId": "963396d7-c96f-4bb1-a24c-42e868a8823d"
}

=== folio-org/mod-patron/src/test/resources/PatronServicesResourceImpl/post_patron_account_instance_bff.json
{
  "item" : { },
  "requestDate" : "0002-01-03T00:00:00.000+00:00",
  "status" : "Open - Not yet filled",
  "pickupLocationId" : "servicePointId",
  "cancellationReasonId" : "cancellationReasonId",
  "canceledByUserId" : "cancelledByUserId",
  "cancellationAdditionalInformation" : "cancellationAdditionalInformation",
  "patronComments" : "tlr-response"
}

=== folio-org/mod-patron/src/test/resources/PatronServicesResourceImpl/response_testPostPatronAccountByIdInstanceByInstanceIdHoldNoItemId.json
{
  "requestId": "d0f032db-9579-443e-a2ac-6add937f4aa2",
  "requestDate": "2021-09-06T15:37:55.000+00:00",
  "item": {
    "instanceId": "23611f0b-35cc-4f40-af09-75907d7cc421",
    "title": "A semantic web primer",
    "author": "Antoniou, Grigoris; Van Harmelen, Frank"
  },
  "queuePosition": 1,
  "expirationDate": "3000-01-30T08:16:30Z",
  "status": "Open - Not yet filled",
  "pickupLocationId": "c4c90014-c8c9-4ade-8f24-b5e313319f4b",
  "patronComments": "I need this book. Instance level comment."
}
