=== folio-org/mod-patron/ramls/loan.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Patron Loan Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
      "description": "The id of the loan"
    },
    "item": {
      "type": "object",
      "description": "The item that is loaned out",
      "$ref": "item.json"
    },
    "loanDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date the item was loaned out"
    },
    "dueDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date the item is due"
    },
    "overdue": {
      "type": "boolean",
      "description": "Indicates if the item is overdue"
    }
  },
  "required": [
    "item",
    "loanDate",
    "dueDate",
    "overdue"
  ]
}

=== folio-org/mod-patron/src/test/resources/PatronServicesResourceImpl/response_testPostPatronAccountByIdItemByItemIdRenew.json
{
    "id": "e15ab05e-e06f-4f31-952b-4eb9933b20e1",
    "item": {
        "instanceId": "85860515-dff2-4506-be78-1b4e104d0305",
        "itemId": "32e5757d-6566-466e-b69d-994eb33d2b62",
        "title": "I Am Renewed!",
        "author": "McBoatface, Boaty"
    },
    "loanDate": "2018-06-11T21:13:03.000+00:00",
    "dueDate": "2025-08-11T21:13:03.000+00:00",
    "overdue": false
}

=== folio-org/mod-patron/ramls/examples/loan.json
{
  "id": "9a171a89-baca-4f1a-b2c4-d7253854864e",
  "item": {
    "instanceId": "6e024cd5-c19a-4fe0-a2cd-64ce5814c694",
    "itemId": "7d9dfe70-0158-489d-a7ed-2789eac277b3",
    "title": "Some Book About Something",
    "author": "Some Guy; Another Guy"
  },
  "loanDate": "2018-06-01T11:12:00.000+0000",
  "dueDate": "2525-01-01T11:12:00.000+0000",
  "overdue": false
}
