=== folio-org/mod-patron/ramls/staging_userdata.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Staging User Information Schema",
  "description": "A staging user",
  "javaName": "StagingUser",
  "type": "object",
  "properties": {
    "id": {
      "description" : "A globally unique (UUID) identifier for the user",
      "type": "string"
    },
    "isEmailVerified": {
      "description": "A flag to determine if a patron is activated.",
      "type": "boolean"
    },
    "minor": {
      "description": "An optional flag If true, the user will be assigned to the 'Basic -- Minor (INTERNAL)' patron group upon creation; otherwise if false or null, the 'Remote Non-circulating' group is assigned.",
      "type": "boolean"
    },
    "status": {
      "type": "string",
      "description": "whether tier-1 or tier-2",
      "enum": ["TIER-1", "TIER-2"]
    },
    "externalSystemId": {
      "description": "A unique ID (UUID) that corresponds to an external authority",
      "type": "string"
    },
    "generalInfo": {
      "type": "object",
      "description": "General info of staging user",
      "properties": {
        "firstName": {
          "type": "string",
          "description": "The staging user's given name"
        },
        "preferredFirstName": {
          "type": "string",
          "description": "The user's preferred name"
        },
        "middleName": {
          "type": "string",
          "description": "The staging user's middle name (if any)"
        },
        "lastName": {
          "type": "string",
          "description": "The staging user's surname"
        }
      },
      "required": ["firstName", "lastName"],
      "additionalProperties": false
    },
    "addressInfo": {
      "type": "object",
      "description": "Primary address info of staging user",
      "properties": {
        "addressLine0": {
          "type": "string",
          "description": "Address, Line 0"
        },
        "addressLine1": {
          "type": "string",
          "description": "Address, Line 1"
        },
        "city": {
          "type": "string",
          "description": "City name"
        },
        "province": {
          "type": "string",
          "description": "Province"
        },
        "zip": {
          "type": "string",
          "description": "Zip Code"
        },
        "country": {
          "type": "string",
          "description": "Country"
        }
      },
      "additionalProperties": false
    },
    "contactInfo": {
      "type": "object",
      "description": "Contact info of staging user",
      "properties": {
        "phone": {
          "type": "string",
          "description": "The user's primary phone number"
        },
        "mobilePhone": {
          "type": "string",
          "description": "The user's mobile phone number"
        },
        "email": {
          "type": "string",
          "description": "The user's email address",
          "format": "email"
        }
      },
      "required": ["email"],
      "additionalProperties": false
    },
    "preferredEmailCommunication": {
      "type": "array",
      "description": "Email communication info of staging user",
      "items": {
        "type": "string",
        "enum": ["Support", "Programs", "Services"]
      },
      "maxItems": 3,
      "uniqueItems": true
    },
    "metadata": {
      "type": "object",
      "$ref": "raml-util/schemas/metadata.schema"
    }
  },
  "required": ["generalInfo", "contactInfo"],
  "additionalProperties": false
}

=== folio-org/mod-patron/src/test/resources/PatronServicesResourceImpl/staging-users-post-response.json
{
  "id": "http_status_200",
  "isEmailVerified": true,
  "status": "TIER-1",
  "generalInfo": {
    "firstName": "test1",
    "middleName": "www",
    "lastName": "new-record-1"
  },
  "addressInfo": {
    "addressLine0": "123 Main St",
    "addressLine1": "Apt 4B",
    "city": "Metropolis",
    "province": "NY",
    "zip": "12345",
    "country": "USA"
  },
  "contactInfo": {
    "phone": "555-123456",
    "mobilePhone": "555-5678",
    "email": "new-record-kapil_new3@test.com"
  },
  "preferredEmailCommunication": [
    "Programs",
    "Support",
    "Services"
  ],
  "metadata": {
    "createdDate": "2024-10-15T10:50:36.267+00:00",
    "createdByUserId": "21457ab5-4635-4e56-906a-908f05e9233b",
    "updatedDate": "2024-10-17T09:32:24.840+00:00",
    "updatedByUserId": "21457ab5-4635-4e56-906a-908f05e9233b"
  }
}

=== folio-org/mod-patron/src/test/resources/PatronServicesResourceImpl/staging-users-post-request.json
{
  "isEmailVerified": false,
  "status": "TIER-1",
  "generalInfo": {
    "firstName": "TEST_STATUS_CODE_200",
    "middleName": "www",
    "lastName": "new-record-1"
  },
  "addressInfo": {
    "addressLine0": "123 Main St",
    "addressLine1": "Apt 4B",
    "city": "Metropolis",
    "province": "NY",
    "zip": "12345",
    "country": "USA"
  },
  "contactInfo": {
    "phone": "555-123456",
    "mobilePhone": "555-5678",
    "email": "new-record-kapil_new3@test.com"
  },
  "preferredEmailCommunication": [
    "Programs",
    "Support",
    "Services"
  ]
}
