=== folio-org/mod-patron/ramls/userdata.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "User Schema",
  "description": "A user",
  "javaName": "User",
  "type": "object",
  "properties": {
    "username": {
      "description": "A unique name belonging to a user. Typically used for login",
      "type": "string"
    },
    "id": {
      "description" : "A globally unique (UUID) identifier for the user",
      "type": "string"
    },
    "externalSystemId": {
      "description": "A unique ID that corresponds to an external authority",
      "type": "string"
    },
    "barcode": {
      "description": "The unique library barcode for this user",
      "type": "string"
    },
    "active": {
      "description": "A flag to determine if the user's account is effective and not expired. The tenant configuration can require the user to be active for login. Active is different from the loan patron block",
      "type": "boolean"
    },
    "type": {
      "description": "The class of user like staff or patron; this is different from patronGroup; it can store shadow, system user and dcb types also",
      "type": "string"
    },
    "patronGroup": {
      "description": "A UUID corresponding to the group the user belongs to, see /groups API, example groups are undergraduate and faculty; loan rules, patron blocks, fees/fines and expiration days can use the patron group",
      "type": "string",
      "$ref": "raml-util/schemas/uuid.schema"
    },
    "departments": {
      "description": "A list of UUIDs corresponding to the departments the user belongs to, see /departments API",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "$ref": "raml-util/schemas/uuid.schema"
      }
    },
    "meta": {
      "description": "Deprecated",
      "type": "object"
    },
    "proxyFor": {
      "description" : "Deprecated",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "personal": {
      "description": "Personal information about the user",
      "type": "object",
      "properties": {
        "lastName": {
          "description": "The user's surname",
          "type": "string"
        },
        "firstName": {
          "description": "The user's given name",
          "type": "string"
        },
        "middleName": {
          "description": "The user's middle name (if any)",
          "type": "string"
        },
        "preferredFirstName": {
          "description": "The user's preferred name",
          "type": "string"
        },
        "email": {
          "description": "The user's email address",
          "type": "string"
        },
        "phone": {
          "description": "The user's primary phone number",
          "type": "string"
        },
        "mobilePhone": {
          "description": "The user's mobile phone number",
          "type": "string"
        },
        "dateOfBirth": {
          "type": "string",
          "description": "The user's birth date",
          "format": "date-time"
        },
        "addresses": {
          "description": "Physical addresses associated with the user",
          "type": "array",
          "minItems": 0,
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "description": "A unique id for this address",
                "type": "string"
              },
              "countryId": {
                "description": "The country code for this address",
                "type": "string"
              },
              "addressLine1": {
                "description": "Address, Line 1",
                "type": "string"
              },
              "addressLine2": {
                "description": "Address, Line 2",
                "type": "string"
              },
              "city": {
                "description": "City name",
                "type": "string"
              },
              "region": {
                "description": "Region",
                "type": "string"
              },
              "postalCode": {
                "description": "Postal Code",
                "type": "string"
              },
              "addressTypeId": {
                "description": "A UUID that corresponds with an address type object",
                "type": "string",
                "$ref": "raml-util/schemas/uuid.schema"
              },
              "primaryAddress": {
                "description": "Is this the user's primary address?",
                "type": "boolean"
              }
            },
            "required":[
              "addressTypeId"
            ],
            "additionalProperties": false
          }
        },
        "preferredContactTypeId": {
          "description": "Id of user's preferred contact type like Email, Mail or Text Message, see /addresstypes API",
          "type": "string"
        },
        "profilePictureLink": {
          "description": "Link to the profile picture",
          "type": "string",
          "format": "uri"
        }
      },
      "additionalProperties": false,
      "required": [
        "lastName"
      ]
    },
    "enrollmentDate": {
      "description": "The date in which the user joined the organization",
      "type": "string",
      "format": "date-time"
    },
    "expirationDate": {
      "description": "The date for when the user becomes inactive",
      "type": "string",
      "format": "date-time"
    },
    "createdDate": {
      "description": "Deprecated",
      "type": "string",
      "format": "date-time"
    },
    "updatedDate": {
      "description": "Deprecated",
      "type": "string",
      "format": "date-time"
    },
    "metadata": {
      "type": "object",
      "$ref": "raml-util/schemas/metadata.schema"
    },
    "tags": {
      "type": "object",
      "$ref": "raml-util/schemas/tags.schema"
    },
    "customFields" : {
      "description": "Object that contains custom field",
      "type": "object",
      "additionalProperties": true
    },
    "preferredEmailCommunication": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["Support", "Programs", "Services"]
      },
      "maxItems": 3,
      "uniqueItems": true,
      "description": "Preferred email communication types"
    }
  },
  "additionalProperties": false
}

=== folio-org/mod-patron/ramls/examples/user.json
{
  "username": "jhandey",
  "id": "7261ecaae3a74dc68b468e12a70b1aec",
  "active": true,
  "type": "patron",
  "patronGroup": "4bb563d9-3f9d-4e1e-8d1d-04e75666d68f",
  "meta": {
    "creation_date": "2016-11-05T0723",
    "last_login_date": ""
  },
  "personal": {
    "lastName": "Handey",
    "firstName": "Jack",
    "preferredFirstName": "Jackie",
    "email": "jhandey@biglibrary.org",
    "phone": "2125551212"
  }
}
